spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

security:
  oauth2:
    resource:
      user-info-uri:  https://sunshine-auth-service.cfapps.io/user/me
---
spring:
  profiles: local, default

server:
  port: 7979

eureka:
  client:
    enabled: true

logging:
  level:
    org:
      springframework: DEBUG

---
spring:
  profiles: cloud
management:
  endpoints:
    web:
      exposure:
        include: "*"
  cloud:
    config:
      discovery:
        enabled: false
        serviceId: sunshine-config-server
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: https://sunshine-eureka.cfapps.io/eureka
    enabled: true
