---
spring:
  profiles: local, default

server:
  port: 7979

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      springframework: DEBUG

security:
  oauth2:
    resource:
      user-info-uri:  https://sunshine-auth-service.cfapps.io/user/me
---
spring:
  profiles: cloud