---
spring:
  profiles: local, default

server:
  port: 7979

eureka:
  client:
    enabled: true

logging:
  level:
    org:
      springframework: DEBUG

security:
  oauth2:
    resource:
      user-info-uri:  https://sunshine-auth-service.cfapps.io/user/me
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.sunshine-eureka-server.credentials.url}
    enabled: true